spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource	#使用druid连接池
    druid:
      url: jdbc:mysql://localhost:3306/homework3
      username: root
      password: mhr12345
      driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8080
  servlet:
    context-path: /
  address: 0.0.0.0